### ISSUE TITLE
hello world html

### ISSUE THREAD

**Issue by Xester22** [newridho/Halo-Dunia#21]
# want to add hello world html code
please assign me for it and dont forget to add the hacktober fest label

**Comment by newridho** [comment]
Of course, please

**Comment by Morbius00** [comment]
> Of course, please

Please add the hactober fest label

**Comment by Xester22** [comment]
> Of course, please
Please add the hactober label

**Comment by newridho** [comment]
> > Of course, please
> > Please add the hactober label

but you haven't contributed at all

**Comment by Xester22** [comment]
> > > Of course, please
> > > Please add the hactober label
> 
> Okay, but you haven't contributed at all

Yea actually this is my new account

**Comment by Xester22** [comment]
> > > > Of course, please
> > > > Please add the hactober label
> > 
> > 
> > Okay, but you haven't contributed at all
> 
> Yea actually this is my new account

No issues after getting my pr please add the hactober fest label ...ok
